// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamingAPI.Data;

#nullable disable

namespace ANG_API_Assess.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20251112103928_AddSkipTrackingToUser")]
    partial class AddSkipTrackingToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StreamingAPI.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Album")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Composer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MediaId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Media", (string)null);

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            DurationInMinutes = 4,
                            Genre = 1,
                            MediaType = 1,
                            ReleaseDate = new DateTime(2017, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shape of You",
                            Url = "/media/shapeofyou.mp3"
                        },
                        new
                        {
                            MediaId = 2,
                            DurationInMinutes = 148,
                            Genre = 99,
                            MediaType = 2,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Url = "/media/inception.mp4"
                        });
                });

            modelBuilder.Entity("StreamingAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("StreamingAPI.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistId"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlaylistType")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId");

                    b.HasIndex("UserId", "PlaylistType")
                        .IsUnique()
                        .HasFilter("[PlaylistType] = 2");

                    b.ToTable("Playlists", (string)null);

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            IsDefault = true,
                            Name = "Liked Music",
                            PlaylistType = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("StreamingAPI.Models.PlaylistMedia", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("PlaylistMedias", (string)null);

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            MediaId = 1
                        },
                        new
                        {
                            PlaylistId = 1,
                            MediaId = 2
                        });
                });

            modelBuilder.Entity("StreamingAPI.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("SubscriptionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionPlanId"));

                    b.Property<string>("AudioQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanCreatePlaylists")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSeekInSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDownloadAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDevices")
                        .HasColumnType("int");

                    b.Property<int>("MaxSkipsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("PlanName")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            SubscriptionPlanId = 1,
                            AudioQuality = "128kbps",
                            CanCreatePlaylists = false,
                            CanSeekInSongs = false,
                            IsDownloadAllowed = false,
                            MaxDevices = 1,
                            MaxSkipsPerDay = 3,
                            PlanName = 1,
                            Price = 0m
                        },
                        new
                        {
                            SubscriptionPlanId = 2,
                            AudioQuality = "320kbps",
                            CanCreatePlaylists = true,
                            CanSeekInSongs = true,
                            IsDownloadAllowed = true,
                            MaxDevices = 3,
                            MaxSkipsPerDay = 999999,
                            PlanName = 2,
                            Price = 9.99m
                        },
                        new
                        {
                            SubscriptionPlanId = 3,
                            AudioQuality = "FLAC",
                            CanCreatePlaylists = true,
                            CanSeekInSongs = true,
                            IsDownloadAllowed = true,
                            MaxDevices = 5,
                            MaxSkipsPerDay = 999999,
                            PlanName = 3,
                            Price = 14.99m
                        });
                });

            modelBuilder.Entity("StreamingAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSkipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SkipsToday")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "thankyouforcontactingharish@gmail.com",
                            PasswordHash = "KqZ8vX2Np5Yt7Wm3Lq6Ks9Rn1Jq4Hp0Vm8Ls2Xt5Yz7Wm=",
                            PasswordSalt = "Np7Yt2Wz5Vm8Ks1Hp6Jq9Rn3Kp0Xt5Yz8Wm2Lq7Np4Ks6=",
                            Role = 3,
                            SkipsToday = 0,
                            SubscriptionPlanId = 2,
                            UserName = "AdminUser"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "john@example.com",
                            PasswordHash = "Xp2Yz7Wm3Lq6Ks5Np8Rn1Jq4Yt0Vm9Ls2Hp7Kp3Xt6Wz5=",
                            PasswordSalt = "Lq4Np7Yt2Wz5Vm8Ks1Hp6Jq9Rn3Kp0Xt5Yz8Wm2Lq7Np4=",
                            Role = 1,
                            SkipsToday = 0,
                            SubscriptionPlanId = 1,
                            UserName = "JohnDoe"
                        });
                });

            modelBuilder.Entity("StreamingAPI.Models.Media", b =>
                {
                    b.HasOne("StreamingAPI.Models.User", "Creator")
                        .WithMany("UploadedMedia")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("StreamingAPI.Models.Payment", b =>
                {
                    b.HasOne("StreamingAPI.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamingAPI.Models.Playlist", b =>
                {
                    b.HasOne("StreamingAPI.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamingAPI.Models.PlaylistMedia", b =>
                {
                    b.HasOne("StreamingAPI.Models.Media", "Media")
                        .WithMany("PlaylistMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingAPI.Models.Playlist", "Playlist")
                        .WithMany("PlaylistMedias")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("StreamingAPI.Models.User", b =>
                {
                    b.HasOne("StreamingAPI.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionPlanId");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("StreamingAPI.Models.Media", b =>
                {
                    b.Navigation("PlaylistMedias");
                });

            modelBuilder.Entity("StreamingAPI.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistMedias");
                });

            modelBuilder.Entity("StreamingAPI.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("StreamingAPI.Models.User", b =>
                {
                    b.Navigation("Playlists");

                    b.Navigation("UploadedMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
